# Generated by Django 5.2.6 on 2025-11-04 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_name', models.CharField(max_length=50)),
                ('attempts', models.IntegerField()),
                ('level', models.CharField(max_length=10)),
                ('date_played', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
