# Generated by Django 5.2.6 on 2025-11-04 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='score',
            name='time_taken',
            field=models.FloatField(default=10, help_text='Seconds taken to guess correctly'),
            preserve_default=False,
        ),
    ]
